version: '3.6'
services:
  python-kafka:
    image: centos:7
    build: .
    ports:
      - 2181:2181
      - 9092:9092
      - 8081:8081
      - 9995:9995
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./dockershare:/dockershare
    build:
      context: ./
      dockerfile: Dockerfile
    command: tail -f /dev/null
